// src/app/app.jsx
// @flow

import * as ReactDOM from "react-dom";
import * as React from "react";
import { useTranslation } from 'react-i18next';

import { hot } from "react-hot-loader/root";
import { library } from "@fortawesome/fontawesome-svg-core";
import { fab } from "@fortawesome/free-brands-svg-icons";

import './i18n';
/**
 * bootstrap function
 * @return {void}
 */
function bootstrap() {
  console.log(
    "%c90 s r l s\n%cPratiche Auto\nTel 06 01905227",
    "font-size:1.5em;color:#1945D5;",
    "color:#14BD4C;font-size:1em;"
  );
  if (!process.env.PROD) {
    console.log("%cDeveloping mode enabled\n", "color:#a91839;font-size:1em;");
  } else {
    // Install service worker
    intallSW("/studio90srls-sw.js");
  }
  library.add(fab);
  const rootContainer = (document.getElementById("main-container"): any);
  ReactDOM.render(<Studio90srls />, rootContainer);
}

function intallSW(name: string) {
  const serviceWorker = navigator.serviceWorker;
  if (serviceWorker) {
    window.addEventListener("load", () => {
      serviceWorker
        .register(name, { scope: "./" })
        .then(registration => {
          console.log("SW registered: ", registration);
        })
        .catch(registrationError => {
          console.log("SW registration failed: ", registrationError);
        });
    });
  }
}
/**
 * Studio90srls main function componet
 */
function Studio90srls(props) {
  const [t, i18n] = useTranslation();
  return (
    <React.Fragment>
      <p>{t('refactoring')}</p>
    </React.Fragment>
  );
}

export { bootstrap };
export default hot(Studio90srls);

// src/app/app.vue
<script lang="ts">
/**
 * Studio90srls main class
 */
class Studio90srls {
  static bootstrap() {
    console.log("%c90 s r l s\n%cPratiche Auto\nTel 06 01905227",
      "font-size:1.5em;color:#1945D5;", "color:#14BD4C;font-size:1em;");
    if (!process.env.PROD) {
      console.log("%cDeveloping mode enabled\n",
        "color:#a91839;font-size:1em;");
    } else {
      // Install service worker
      intallSW('/studio90srls-sw.js');
    }
  }

}

function intallSW(name: string) {
  const serviceWorker = navigator.serviceWorker;
  if (serviceWorker) {
    window.addEventListener('load', () => {
      serviceWorker.register(name, { scope: './' }).then(registration => {
        console.log('SW registered: ', registration);
      }).catch(registrationError => {
        console.log('SW registration failed: ', registrationError);
      });
    });
  }
}

export default Studio90srls;
</script>
